"""Default buttons seeded on first run when buttons.toml does not exist."""

from .command_button import CommandButton


def get_default_buttons() -> list[CommandButton]:
    essentials = [
        CommandButton(
            name="Disk Usage",
            command="df -h",
            icon_name="hdd",
            color="#99c1f1",
            text_color="#000000",
            show_output=True,
            tooltip="Show disk space usage for all mounted filesystems",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Memory Usage",
            command="free -h",
            icon_name="memory",
            color="#8ff0a4",
            text_color="#000000",
            show_output=True,
            tooltip="Show total, used and free RAM and swap memory",
            category="Linux Essentials",
        ),
        CommandButton(
            name="CPU Load",
            command="uptime && echo && top -bn1 | head -15",
            icon_name="cpu",
            color="#ffbe6f",
            text_color="#000000",
            show_output=True,
            tooltip="Show system uptime, load averages and top CPU processes",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Temperature",
            command="sensors 2>/dev/null || echo 'lm-sensors is not installed.\nTo install: sudo apt install lm-sensors && sudo sensors-detect'",
            icon_name="thermometer-half",
            color="#ff7800",
            text_color="#000000",
            show_output=True,
            tooltip="Show CPU and GPU temperatures (requires lm-sensors)",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Running Processes",
            command="ps aux --sort=-%cpu | head -20",
            icon_name="activity",
            color="#dc8add",
            text_color="#000000",
            show_output=True,
            tooltip="List top 20 processes sorted by CPU usage",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Network Interfaces",
            command="ip addr",
            icon_name="ethernet",
            color="#62a0ea",
            text_color="#000000",
            show_output=True,
            tooltip="Show all network interfaces and their IP addresses",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Active Connections",
            command="ss -tp state established",
            icon_name="plug",
            color="#57e389",
            text_color="#000000",
            show_output=True,
            tooltip="Show all active TCP connections and the processes using them",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Open Ports",
            command="ss -tulpn",
            icon_name="broadcast",
            color="#57e389",
            text_color="#000000",
            show_output=True,
            tooltip="List all open TCP/UDP ports and the processes using them",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Block Devices",
            command="lsblk",
            icon_name="stack",
            color="#cdab8f",
            text_color="#000000",
            show_output=True,
            tooltip="List all block devices (disks, partitions, loop devices)",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Largest Directories",
            command="du -sh /* 2>/dev/null | sort -rh | head -15",
            icon_name="folder2",
            color="#e5a50a",
            text_color="#000000",
            show_output=True,
            tooltip="Show the 15 largest top-level directories by disk usage",
            category="Linux Essentials",
        ),
        CommandButton(
            name="System Info",
            command="uname -a && echo && lsb_release -a 2>/dev/null || cat /etc/os-release",
            icon_name="info-circle",
            color="#f9f06b",
            text_color="#000000",
            show_output=True,
            tooltip="Show kernel version and Linux distribution information",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Logged-in Users",
            command="w",
            icon_name="people",
            color="#c061cb",
            text_color="#000000",
            show_output=True,
            tooltip="Show who is logged in and what they are doing",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Last Logins",
            command="last | head -20",
            icon_name="person-check",
            color="#9141ac",
            text_color="#000000",
            show_output=True,
            tooltip="Show the last 20 login and logout events",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Failed Services",
            command="systemctl --failed",
            icon_name="exclamation-triangle",
            color="#f66151",
            text_color="#000000",
            show_output=True,
            tooltip="List all systemd services that have failed — useful for diagnosing broken features",
            category="Linux Essentials",
        ),
        CommandButton(
            name="System Journal",
            command="journalctl -n 50 --no-pager",
            icon_name="journal-text",
            color="#ffa348",
            text_color="#000000",
            show_output=True,
            tooltip="Show the last 50 lines of the system journal (all services, cross-distro)",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Kernel Messages",
            command="dmesg | tail -30",
            icon_name="cpu",
            color="#ffa348",
            text_color="#000000",
            show_output=True,
            tooltip="Show the last 30 kernel ring buffer messages (hardware, boot events)",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Clear Trash",
            command="rm -rf ~/.local/share/Trash/files/* ~/.local/share/Trash/info/* 2>/dev/null && echo 'Trash cleared.'",
            icon_name="trash",
            color="#865e3c",
            text_color="#ffffff",
            confirm_before_run=True,
            tooltip="Permanently delete all files in the Trash",
            category="Linux Essentials",
        ),
        CommandButton(
            name="System Update",
            command="bash -c 'if command -v apt >/dev/null 2>&1; then sudo apt update && sudo apt upgrade -y; elif command -v dnf >/dev/null 2>&1; then sudo dnf upgrade -y; elif command -v pacman >/dev/null 2>&1; then sudo pacman -Syu --noconfirm; else echo \"Unknown package manager\"; fi'",
            icon_name="cloud-download",
            color="#62a0ea",
            text_color="#000000",
            show_output=True,
            confirm_before_run=True,
            tooltip="Refresh package lists and upgrade all installed packages (apt / dnf / pacman)",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Reboot",
            command="systemctl reboot",
            icon_name="arrow-clockwise",
            color="#f8e45c",
            text_color="#000000",
            confirm_before_run=True,
            tooltip="Reboot the system immediately",
            category="Linux Essentials",
        ),
        CommandButton(
            name="Shutdown",
            command="systemctl poweroff",
            icon_name="power",
            color="#f66151",
            text_color="#000000",
            confirm_before_run=True,
            tooltip="Power off the system immediately",
            category="Linux Essentials",
        ),
    ]

    development = [
        CommandButton(
            name="Git Status",
            command="git status",
            icon_name="git",
            color="#dc8add",
            text_color="#000000",
            show_output=True,
            tooltip="Show working tree status (staged, unstaged, untracked files)",
            category="Development",
        ),
        CommandButton(
            name="Git Log",
            command="git log --oneline -15",
            icon_name="clock-history",
            color="#c061cb",
            text_color="#000000",
            show_output=True,
            tooltip="Show the last 15 commits in compact one-line format",
            category="Development",
        ),
        CommandButton(
            name="Git Diff",
            command="git diff",
            icon_name="file-earmark-diff",
            color="#cdab8f",
            text_color="#000000",
            show_output=True,
            tooltip="Show unstaged changes in the current working directory",
            category="Development",
        ),
        CommandButton(
            name="Docker PS",
            command="docker ps",
            icon_name="box-seam",
            color="#99c1f1",
            text_color="#000000",
            show_output=True,
            tooltip="List currently running Docker containers",
            category="Development",
        ),
        CommandButton(
            name="Docker PS All",
            command="docker ps -a",
            icon_name="box-seam",
            color="#62a0ea",
            text_color="#000000",
            show_output=True,
            tooltip="List all Docker containers including stopped ones",
            category="Development",
        ),
        CommandButton(
            name="Docker Images",
            command="docker images",
            icon_name="stack",
            color="#62a0ea",
            text_color="#000000",
            show_output=True,
            tooltip="List all locally available Docker images",
            category="Development",
        ),
        CommandButton(
            name="Docker Clean",
            command="docker system prune -f",
            icon_name="trash",
            color="#f66151",
            text_color="#000000",
            confirm_before_run=True,
            show_output=True,
            tooltip="Remove all stopped containers, unused networks, dangling images and build cache",
            category="Development",
        ),
        CommandButton(
            name="Tail Syslog",
            command="tail -n 50 /var/log/syslog 2>/dev/null || journalctl -n 50 --no-pager",
            icon_name="file-text",
            color="#ffa348",
            text_color="#000000",
            show_output=True,
            tooltip="Show the last 50 lines of the system log (syslog or journald)",
            category="Development",
        ),
        CommandButton(
            name="Disk I/O",
            command="iostat -x 1 3 2>/dev/null || echo 'iostat not found. Install: sudo apt install sysstat'",
            icon_name="hdd",
            color="#cdab8f",
            text_color="#000000",
            show_output=True,
            tooltip="Show disk I/O statistics (3 samples, 1 second apart) — requires sysstat",
            category="Development",
        ),
        CommandButton(
            name="Python Version",
            command="python3 --version && pip3 --version",
            icon_name="filetype-py",
            color="#f9f06b",
            text_color="#000000",
            show_output=True,
            tooltip="Show installed Python 3 and pip versions",
            category="Development",
        ),
        CommandButton(
            name="Pip Outdated",
            command="pip3 list --outdated 2>/dev/null | head -20 || echo 'pip3 not found'",
            icon_name="filetype-py",
            color="#e5a50a",
            text_color="#000000",
            show_output=True,
            tooltip="List Python packages that have newer versions available",
            category="Development",
        ),
        CommandButton(
            name="Node Version",
            command="node --version && npm --version",
            icon_name="filetype-js",
            color="#8ff0a4",
            text_color="#000000",
            show_output=True,
            tooltip="Show installed Node.js and npm versions",
            category="Development",
        ),
        CommandButton(
            name="NPM Outdated",
            command="npm outdated 2>/dev/null || echo 'npm not found or not in a Node project'",
            icon_name="filetype-js",
            color="#57e389",
            text_color="#000000",
            show_output=True,
            tooltip="List npm packages with newer versions available (run from a Node project folder)",
            category="Development",
        ),
        CommandButton(
            name="Listening Services",
            command="ss -tlnp",
            icon_name="broadcast",
            color="#57e389",
            text_color="#000000",
            show_output=True,
            tooltip="List all services listening on TCP ports",
            category="Development",
        ),
    ]

    buttons = essentials + development
    for i, btn in enumerate(buttons):
        btn.position = i
        btn.is_default = True
    return buttons
